---
Name: fluentworkflow
After:
  - '#fluent*'
  - '#workflowconfig'
---
SilverStripe\Core\Injector\Injector:
  Symbiote\AdvancedWorkflow\Services\WorkflowService:
    class: WebbuildersGroup\FluentWorkflow\Services\FluentWorkflowService
  Symbiote\AdvancedWorkflow\Extensions\WorkflowApplicable:
    class: WebbuildersGroup\FluentWorkflow\Extensions\FluentWorkflowApplicable
  Symbiote\QueuedJobs\Services\QueuedJobService:
    class: WebbuildersGroup\FluentWorkflow\Services\FluentQueuedJobService


SilverStripe\CMS\Model\SiteTree:
  extensions:
    - WebbuildersGroup\FluentWorkflow\Extensions\FluentWorkflowApplicable
